name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      on_main: ${{ steps.ensure-main.outputs.on_main }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tag commit is on main
        id: ensure-main
        run: |
          git fetch origin main --depth=1
          if git merge-base --is-ancestor "${GITHUB_SHA}" "origin/main"; then
            echo "on_main=true" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::Skipping deploy: tag ${GITHUB_REF_NAME} is not on main"
            echo "on_main=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node.js
        if: steps.ensure-main.outputs.on_main == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        if: steps.ensure-main.outputs.on_main == 'true'
        run: npm ci

      - name: Build
        if: steps.ensure-main.outputs.on_main == 'true'
        run: npm run build

      - name: Archive distribution artifact
        if: steps.ensure-main.outputs.on_main == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: gcode-viewer-${{ github.ref_name }}
          path: dist
          if-no-files-found: error

      - name: Upload artifact
        if: steps.ensure-main.outputs.on_main == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    if: needs.build.outputs.on_main == 'true'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
